### ISSUE TITLE
pq panic on `make db-create-development`

### ISSUE THREAD

**Issue by Drakevr** [kokeroulis/modip#6]
system: Slackware-current x86_64 (dockerized)
with psql 9.3, go1.3.3, node 0.10.32, npm 1.4, bower 1.3.12
everything runs in the same docker container.

username: tsiapaliokas
password: tsiapaliokas

```
Can't connect to postgresql
panic: pq: password authentication failed for user "tsiapaliokas"

goroutine 16 [running]:
runtime.panic(0x821620, 0xc2080d4360)
    /usr/lib64/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/kokeroulis/modip/db.Connect()
    /home/tsiapaliokas/Github/github.com/kokeroulis/modip/.vendor/src/github.com/kokeroulis/modip/db/setup.go:24 +0x253
main.main()
    /home/tsiapaliokas/Github/github.com/kokeroulis/modip/modip.go:17 +0xa2

goroutine 19 [finalizer wait]:
runtime.park(0x412f30, 0xae7528, 0xae4f09)
    /usr/lib64/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xae7528, 0xae4f09)
    /usr/lib64/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/lib64/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/lib64/go/src/pkg/runtime/proc.c:1445

goroutine 20 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208046000)
    /usr/lib64/go/src/pkg/database/sql/sql.go:583 +0x48
created by database/sql.Open
    /usr/lib64/go/src/pkg/database/sql/sql.go:442 +0x27c

goroutine 17 [syscall]:
runtime.goexit()
    /usr/lib64/go/src/pkg/runtime/proc.c:1445
exit status 2
make: *** [db-create-development] Error 1
```

relevant pg_hba part. 

``` conf
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     md5
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
```

**Comment by gtsiap** [comment]
Its a slackware specific issue, it works on vader and in my machine!!!!
I am kidding.  Seriously now. 

I have _really_ tried to make the installation something like 5 copy&paste commands and you are done, but this comes with a cost. The issue here is that drake has a different pg_hda from the rest which is better and more secure. My pg_hda is insecure and it focuses on the 5 copy&paste commands approach.

The contents of Makefile and the scripts that they execute should be used only as a reference,
in a production enviroment they should be modified, which is what drake is trying to setup.

The issue is that drake is using "md5" as an authentication method, but I use "trust".
Setting all the users to "md5" means that _ALL_ of them must have a password even the pg admin(postgres). In most distros the pg admin doesn't have a password(does it have one in slackware???). So there is no way to make my scripts to just work with every single setup. The postgresql configuration has to be done manually.

I have improved the configuration handling in modip, check modip.conf it will need some modification. 

Modip can be configured with my scripts only if you add in pg_hda.conf this

`local   all   postgres   trust`

Modip can handle the db user if he has a password but not if the pg admin has one.

I have moved almost all the db code in go in order to make my scripts less mandatory.
The only thing that my scripts do regarding the db is to create the pg extentions.

So in a production enviroment in order to install modip someone must,
- install go, node, postgresql, redis
- configure postgresql and redis
- install modip
- bower install
- create the pg extentions
- modify modip.conf

Can we mark this as solved?

**Comment by Drakevr** [comment]
I see, i will create a specialized container to test if that way for now, i don't like this though...

**Comment by gtsiap** [comment]
> i don't like this though... 

Then don't close the issue :)

With your sysadmin hat on, which configuration would you like to see on the server and what would you like from modip do?
